server:
  port: 8080
limit-service:
  min: 11
  max: 11111
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cur_app
    password: anything
    url: jdbc:mysql://localhost:3306/cur_proj?createDatabaseIfNotExist=true

